config/routes.rb
Rails.application.routes.draw do
  get 'messages/show'
  post "messages" => "messages#create"

  get 'members/index'
  get 'members/show'

  get 'groups/index' => "groups#index"
  get 'groups/show'
  get 'groups/new'
  post 'groups' => "groups#create"

  get "groups/my_group"
  get "groups/group"
  get "groups/out_top/:id" => "groups#out_top"
  get "groups/top/:id" => "groups#top"
  get "groups/top_page/:id" => "groups#top_page"
  get "groups/waiting/:id" => "groups#waiting"
  get "groups/delete/:id" => "groups#delete"
  get "groups/delete_member/:id" => "groups#delete_member"

  get "members/application/:id" => "members#application"
  get "members/applicate/:id" => "members#applicate"
  get "members/applicater/:id" => "members#applicater"
  get "members/permit/:group_id&:user_id" => "members#permit"
  get "members/delete/:group_id&:user_id" => "members#delete"
  get "members/retire" => "members#retire"

  get 'users/index'
  get 'users/show'

  get 'events/index'
  get 'events/new'
  get 'events/new_from_cal'
  post 'events' => 'events#create'

  get 'events/show/:e_id' => 'events#show'
  get 'events/delete/:e_id' => 'events#delete'
  get 'events/edit/:e_id' => 'events#edit'
  get 'events/attend/:e_id' => 'events#attend'
  get 'events/absence/:e_id' => 'events#absence'
  get 'events/calender/:num' => 'events#calender'
  get "events/exit"
  get "events/neoindex"

  get "posts/club_list"

#  get 'posts/_calender' => 'events#all'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, :only => [:index, :show]
  as :user do
    get 'users/edit', :to => 'users/registrations#edit', :as => :user_root
  end


  resources :posts do
    resources :comments, only: [:create, :destroy]
  end

  root 'groups#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  validates :body, presence: true
end

app/models/event.rb
class Event < ApplicationRecord
  validates :title, presence: true
  validates :about, presence: true
end

app/models/group.rb
class Group < ApplicationRecord
  validates :name, presence: true

  def self.search(search)
    if search.present?
      Group.where(['name LIKE ?', "%#{search}%"])
    else
      Group.all
    end
  end

end

app/models/member.rb
class Member < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
  validates :body, presence: true
end

app/models/p_member.rb
class PMember < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  # @post.comments とかけるようになる
  validates :title, presence: true, length: { minimum: 3, message: 'タイトルが短すぎます (3文字以上)'}
  validates :body, presence: true

  def self.search(search)
    if search.present?
      Post.where(['title LIKE ?', "%#{search}%"])
    else
      Post.all
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :image, ImageUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable#, :confirmable

  #後で変更する
  validates :username, presence: true, length: { in: 1..15 }
  #validates :comment, length: { in: 0..100 }
  validates :age, :numericality => {:only_integer => true, :allow_nil => true}
  #validates :age, numericality: true
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  #ログイン者のみ表示
  before_action :authenticate_user!

  def delete
    @group = Group.where("id = ?", params[:id]).first
    if @group.master_id != current_user.id then
    redirect_to "no_title"
    else
    @group.destroy
    @member = Member.where("group_id = ?", params[:id])
    @member.destroy_all
    @user = User.where("state_group_id = ?", current_user.state_group_id).first
    @user.state_group_id = -1
    @user.save
    redirect_to "/posts/club_list"
    end
  end

  def delete_member
    @member = Member.where("group_id = ?", params[:id]).where("user_id = ?", current_user.id).first
    @member.destroy
    redirect_to root_path
  end

  def new
    @group = Group.new
  end

  def update
  end

  def index
    @groups = Group.search(params[:search]).order(created_at: 'desc')
    @tmp = params[:search]
  end

  def show
  end

  def waiting
    @group = Group.where("id = ?", params[:id]).first
  end

  def create

    if params[:group][:group_id] != nil then
      @group = Group.where("id = ?", params[:group][:group_id]).first
      @group.name = params[:group][:name]
      @group.about = params[:group][:about]

      if @group.save
        redirect_to "/posts/club_list"
      else
        redirect_to "/members/applicater/#{@group.id}", flash: {name_error: "団体名が入力されていません"}
      end
    elsif params[:group][:group_id] == nil then
       @group = Group.new
       @group.name = params[:group][:name]
       @group.master_id = current_user.id
       @group.master_name = current_user.username
       @group.about = params[:group][:about]
       if @group.save
         redirect_to "/posts/club_list"
       else
         redirect_to "/groups/new", flash: {name_error: "団体名が入力されていません"}
       end
    end
  end

  def out_top
    @group_id = params[:id]
  end

  def top
    @group_id = params[:id]
    @group = Group.where("id = ?", @group_id).first
    @member = Member.where("group_id = ?", @group_id).where("user_id = ?", current_user.id).first
    if ( @member == nil && ( @group.master_id != current_user.id) ) then
     redirect_to "/members/application/#{@group_id}"
    elsif ( (@group.master_id == current_user.id) || (@member.p == 1) ) then
     @user = User.where("id = ?", current_user.id).first
     @user.state_group_id = @group_id
     @user.save
     redirect_to "/posts"
    elsif @member.p == 0 then
     redirect_to "/groups/waiting/#{@group_id}"
    else
    end
  end

  def top_page
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  #ログイン者のみ表示
  before_action :authenticate_user!

  def index
    @posts = Post.search(params[:search]).order(updated_at: 'desc').where("group_id = ?", current_user.state_group_id)
    @tmp = params[:search]
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    #render plain: params[:post].inspect
    #@post = Post.new(params.require(:post).permit(:title, :body))
    @post = Post.new(post_params)
    @post.username = current_user.username
    @post.user_id = current_user.id
    @post.group_id = current_user.state_group_id
    #@post.group_id = @group.id
    if @post.save
      redirect_to posts_path
    else
      #render plain: @post.errors.inspect
      render 'new'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_path
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.username != current_user.username then
    else
      @post.destroy
    end
    redirect_to posts_path
  end

  def club_list
  end


  private
    def post_params
      params.require(:post).permit(:title, :body)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/recruits_helper.rb
module RecruitsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/index.html.erb
<section class="column">

  <div class = "titleposi">
    <h1>Club List</h1>
  </div>

  <!-- 検索機能実装 -->
  <%= form_tag groups_index_path, :method => 'get' do %>
    <p>
      <%= text_field_tag :search , @tmp %>
      <%= submit_tag "Search", :name => nil %>
    </p>
  <% end %>

<div class = "li_box_scrollbar">
  <ul class = "board">

  <% @groups.each do |f| %>

    <li>
      <font size = "5"><%= link_to "#{f.name}", "/groups/out_top/#{f.id}" %></font><br/>
      <% @user = User.where("id = ?", f.master_id).first %>
      管理者: <%= link_to "#{@user.username}", "/users/#{f.master_id}" %>
    </li>
    <% end %>
  </ul>

</div>
</section>

app/views/groups/my_group.html.erb
<section class = "column">
  <div class = "titleposi">
<h1>Management List</h1>
  </div>
  <br/>
<%= link_to "Create!", "/groups/new",class: "link_btn" %>
<% @group = Group.where("master_id = ?", current_user.id) %>
<div class = "box_scrollbar">
<ul class = "board">
<% @group.each do |f| %>
<li>
<%= link_to "#{f.name}", "/groups/out_top/#{f.id}" %>
<%= link_to "[編集]", "/members/applicater/#{f.id}" %>

<% @member = Member.where("group_id = ?", f.id).where("p = ?", 0) %>
<% @i = 0%>
<% @member.each do |c| %>
<% @i = @i + 1 %>
<% end %>
<% if @i != 0 %>
<p align="right">承認待ち: <%= @i %>人</p>
<% end %>
</li>
<% end %>
</ul>
</div>

</section>

app/views/groups/new.html.erb
<section class = "column">
  <div class = "titleposi">
  <h1>新規団体作成</h1>
</div>
  <%= form_for Group.new do |f| %>
  <p>
    <%= f.text_field :name, placeholder: 'Group Name' %>
    <% if flash[:name_error] %>
      <font color="red"><%= flash[:name_error]%></font>
    <% end %>
  </p>

  <p><%= f.text_area :about, :placeholder => "About Group"%></p>

  <%= f.submit :value => "作成する" %>
  <% end %>
  <br/>
</section>

app/views/groups/out_top.html.erb
<section class = "column">
  <div class = "center">
<% @group = Group.where("id = ?", @group_id).first %>
<div class = "titleposi">
<h1><%= @group.name %></h1>
</div>
<p><%= simple_format(@group.about) %></p>


<% @member = Member.where("group_id = ?", @group_id).where("user_id = ?", current_user.id).first %>
<% @group = Group.where("id = ?", @group_id).first %>

<p>
<% if ( @member == nil ) && ( @group.master_id != current_user.id ) then %>

<%= link_to "申請する", "/members/applicate/#{@group_id}", data:{confirm: "「#{@group.name}」への参加を申請しますか?"} ,class:"cross_line"%>

<% elsif ( @group.master_id != current_user.id ) && ( @member.p == 0 ) then %>

<p>現在「<%= @group.name %>」への参加を申請中です。</p>
<p>管理者の承認をお待ちください。</p>
<p><%= link_to "申請を取り消す", "/groups/delete_member/#{@group_id}", data:{confirm: "「#{@group.name}」への申請を取り消しますか?"},class: "cross_line"%>

<% else %>

<% if current_user.state_group_id == -1 || current_user.state_group_id == nil %>
  <%= link_to "入場する", "/groups/top/#{@group.id}" ,class: "cross_line"%>
<% else %>
  <% @g = Group.where("id = ?", current_user.state_group_id).first %>
  <% if @group.id == current_user.state_group_id %>
    <%= link_to "入場する", "/groups/top/#{@group.id}" ,class: "cross_line"%>
  <% else %>
    <%= link_to "入場する", "/groups/top/#{@group.id}", data:{confirm:"現在「#{@g.name}」にログインしています。\n「#{@g.name}」をログアウトしますか?"},class: "cross_line"%>
  <% end %>
<% end %>

<% end %>
</p>

</section>

app/views/groups/show.html.erb
<section class = "column">
<h1>Groups#show</h1>
<p>Find me in app/views/groups/show.html.erb</p>
</section>

app/views/groups/top.html.erb
<h3>Top画面</h3>

app/views/groups/top_page.html.erb
<section class = "column">
<% @group = Group.where("id = ?", params[:id]).first %>
<h3 align="center">Top_page of 「<%= @group.name %>」</h3>
<p align="center">ここに団体のトップページを繋げる</p>
</section>

app/views/groups/update.html.erb
<h3>NoPrint</h3>

app/views/groups/waiting.html.erb
<section class = "column">
<p align="center">現在「<%= @group.name %>」への参加を申請中です。</p>
<p align="center">管理者の承認をお待ちください。</p>
<p align="center"><%= link_to "申請を取り消す", "/groups/delete_member/#{@group.id}"%>
</section>