config/routes.rb
Rails.application.routes.draw do
  get 'messages/show'
  post "messages" => "messages#create"

  get 'members/index'
  get 'members/show'

  get 'groups/index' => "groups#index"
  get 'groups/show'
  get 'groups/new'
  post 'groups' => "groups#create"

  get "groups/my_group"
  get "groups/group"
  get "groups/out_top/:id" => "groups#out_top"
  get "groups/top/:id" => "groups#top"
  get "groups/top_page/:id" => "groups#top_page"
  get "groups/waiting/:id" => "groups#waiting"
  get "groups/delete/:id" => "groups#delete"
  get "groups/delete_member/:id" => "groups#delete_member"

  get "members/application/:id" => "members#application"
  get "members/applicate/:id" => "members#applicate"
  get "members/applicater/:id" => "members#applicater"
  get "members/permit/:group_id&:user_id" => "members#permit"
  get "members/delete/:group_id&:user_id" => "members#delete"
  get "members/retire" => "members#retire"

  get 'users/index'
  get 'users/show'

  get 'events/index'
  get 'events/new'
  get 'events/new_from_cal'
  post 'events' => 'events#create'

  get 'events/show/:e_id' => 'events#show'
  get 'events/delete/:e_id' => 'events#delete'
  get 'events/edit/:e_id' => 'events#edit'
  get 'events/attend/:e_id' => 'events#attend'
  get 'events/absence/:e_id' => 'events#absence'
  get 'events/calender/:num' => 'events#calender'
  get "events/exit"
  get "events/neoindex"

  get "posts/club_list"

#  get 'posts/_calender' => 'events#all'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, :only => [:index, :show]
  as :user do
    get 'users/edit', :to => 'users/registrations#edit', :as => :user_root
  end


  resources :posts do
    resources :comments, only: [:create, :destroy]
  end

  root 'groups#index'

end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  # @post.comments とかけるようになる
  validates :title, presence: true, length: { minimum: 3, message: 'タイトルが短すぎます (3文字以上)'}
  validates :body, presence: true

  def self.search(search)
    if search.present?
      Post.where(['title LIKE ?', "%#{search}%"])
    else
      Post.all
    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  #ログイン者のみ表示
  before_action :authenticate_user!

  def index
    @posts = Post.search(params[:search]).order(updated_at: 'desc').where("group_id = ?", current_user.state_group_id)
    @tmp = params[:search]
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    #render plain: params[:post].inspect
    #@post = Post.new(params.require(:post).permit(:title, :body))
    @post = Post.new(post_params)
    @post.username = current_user.username
    @post.user_id = current_user.id
    @post.group_id = current_user.state_group_id
    #@post.group_id = @group.id
    if @post.save
      redirect_to posts_path
    else
      #render plain: @post.errors.inspect
      render 'new'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_path
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.username != current_user.username then
    else
      @post.destroy
    end
    redirect_to posts_path
  end

  def club_list
  end


  private
    def post_params
      params.require(:post).permit(:title, :body)
    end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_calendar.html.erb
<!--

<% if request.referer == "http://localhost:3000/groups/out_top/#{current_user.state_group_id}" %>

  <% @group = Group.where("id = ?", current_user.state_group_id).first %>
  <% if @group.master_id == current_user.id %>

    <% @member = Member.where("group_id = ?", current_user.state_group_id).where("p = ?", 0) %>
    <% @i = 0 %>
    <% @member.each do |m| %>
    <% @i = @i + 1 %>
    <% end %>    

    <% if @i != 0 %>
      <script type="text/javascript">
        var username = ""
        alert(username + "管理者様へ\n申請が来ています");
      </script>
    <% end %>

  <% end %>

<% end %>

-->

<% today = Date.today%>
<% @events = Event.where("group_id = ?", current_user.state_group_id) %>

  <table align="center">
    <caption>
      <h2>
      <%= "#{today.strftime('%Y年%-m月')}"%>
    </h2>
    </caption>

    <tr>
      <th width="30" height="20"><font color="red">日</font></th>
      <th width="30" height="20">月</th>
      <th width="30" height="20">火</th>
      <th width="30" height="20">水</th>
      <th width="30" height="20">木</th>
      <th width="30" height="20">金</th>
      <th width="30" height="20"><font color="blue">土</font></th>
    </tr>


    <% month = today.strftime('%m')%>
      <% d = today.at_beginning_of_month.at_beginning_of_week(:sunday)%>
        <% 1.upto(6).each do |i| %>
          <tr>
            <% (d..d.end_of_week(:sunday)).each do |c| %>
          <th width = "20" height = "20">
          <font size = "1">
    	  <% @f = 0 %>
          <% if c.strftime('%m') == month then %>

            <% @events.each do |e| %>
	      <% if ( (c.strftime('%Y') == e.year) && (c.strftime('%m') == e.month) && (c.strftime('%d') == e.date) ) then %>

                <% if c.strftime("%-d") == today.strftime("%-d") %>
                  <font color="red">▶︎</font>
                <% else %>
                <% end %>

		<!---------------------------------------------->

		<% if current_user.state_group_id != -1 %><!-- ログイン状態 -->

		  <% @e = Event.where("group_id = ?", current_user.state_group_id).where("year = ?", c.strftime('%Y')).where("month = ?", c.strftime("%m")).where("date = ?", c.strftime("%d")) %>
		  <% if @e != nil then %>
		    <%= link_to "#{c.strftime('%-d')}", events_neoindex_path(:year => c.strftime('%Y'), :month => c.strftime("%-m"), :day => c.strftime("%-d")) ,class: "linkline3"%>
		  <% else%>
		  <% end %>

		<% else %><!-- ログアウト状態 -->

		 <% @e = Event.where("user_id = ?", current_user.id).where("year = ?", c.strftime('%Y')).where("month = ?", c.strftime("%m")).where("date = ?", c.strftime("%d")) %>
		 <% if @e != nil then %>

		   <!--------------------------------------------->
                   <%= link_to "#{c.strftime('%-d')}", events_neoindex_path(:year => c.strftime('%Y'), :month => c.strftime("%-m"), :day => c.strftime("%-d")) %>
		   <!--------------------------------------------->

  		 <% else %>
                 <% end %>

		<% end %>
		<!--------------------------------------------->

		<% @f = 1 %>
                <% break %>
                <% else %>
                <% end %>
                <% end %>
                <% if @f == 0 then %>

                  <% if c.strftime("%-d") == today.strftime("%-d") %>
		    <font color="red">▶︎</font>
                  <% else %>
                  <% end %>

		  <!-- イベントなしの日付表示-->
	          <%= c.strftime("%-d") %>

                  <% else %>
                  <% end %>
		  <% else %>
		  <% end %>
              </font>
            </th>
            <% end %>
          <% d = d + 1.week %>
          </tr>
        <% end %>
  </table>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
<p>
  <%= f.text_field :title, placeholder: 'enter title' %>
  <% if @post.errors.messages[:title].any? %>
  <span class="error"><%= @post.errors.messages[:title][0] %></span>
  <% end %>
</p>
<p>
  <%= f.text_area :body, placeholder: 'enter body text' %>
  <% if @post.errors.messages[:body].any? %>
  <span class="error"><%= @post.errors.messages[:body][0] %></span>
  <% end %>
</p>
<p>
  <%= f.submit  %>
</p>
<% end %>

app/views/posts/_header.html.erb
<div class = "header-fixed">
  <div class = "header-bk">

    <!-- ログイン状態の表示部分 -->

    <% if (current_user != nil)%>
      <div class = "statelog">
      <% if current_user.state_group_id != -1 then %>
      <% @group = Group.where("id = ?", current_user.state_group_id).first %>
      <% if @group != nil then %>
             <%= @group.name %>にログイン中
            <% else %>
            <% end %>
        <% end %>
      </div>

    <%end%>
    <div class = "header_body">

      <% if (current_user != nil)%>


      <div class = "logo_posi">
        <div class= "titlelogo">
          <% if (current_user.state_group_id != -1) %>
            <%= link_to image_tag('logo.png', class: 'logo'), posts_path %>
          <% else %>
            <%= link_to image_tag('logo.png', class: 'logo'), root_path %>
          <% end %>
        </div>
      </div>

      <div class = "menu _posi">
        <ul class = "h_menu">
          <% if (current_user.state_group_id != -1) %>
            <li><%= link_to "Home",posts_path%></li>
            <li><%= link_to "Clublist",root_path%></li>
            <li><%= link_to "Calendar","/events/calender/0"%></li>
            <li><%= link_to "Myclub", "/posts/club_list" %></li>
          <% else %>
            <li><%= link_to "Clublist",root_path%></li>
            <li><%= link_to "Calendar","/events/calender/0"%></li>
            <li><%= link_to "Myclub", "/posts/club_list" %></li>
          <% end%>
        </ul>
      </div>



      <%else%>

      <div class = "Hlogo_posi">
        <div class= "titlelogo">
          <%= link_to image_tag('logo.png', class: 'logo'), posts_path %>
        </div>
      </div>

      <%end%>
    </div>
  </div>
</div>

app/views/posts/_main.html.erb
<%= link_to 'EXIT', '/events/exit' ,class: "logout"%>

<section class = "column">

<% @group = Group.where("id = ?", current_user.state_group_id).first %>
<div class = "titleposi">
  <h1><%= @group.name %></h1>
</div>


  <h3>
    Information
  </h3>

  <%= form_tag posts_path, :method => 'get' do %>
    <p>
      <%= text_field_tag :search , @tmp %>
      <%= submit_tag "Search", :name => nil %>
    </p>
  <% end %>

  <%= link_to 'Add New!', new_post_path, class: "link_btn"%>
  <div class = "box_scrollbar">
      <p>
        <ul class = "board">
            <% @posts.each do |post| %>
            <li >
              <%= post.updated_at.strftime('%Y/%m/%d %H:%M') %>
              <br>
              <font size = "5"><%= link_to post.title, post_path(post) %></font>
            </li>
            <% end %>
        </ul>
      </p>
  </div>
  <%= render "posts/member"%>


<br/>
</section>

<!-- 団体への申請者の有無をお知らせ -->
<!-- ページ移動の際にタイムラグなどの若干のバグあり -->
<!-------------------------------------->

<% if current_user.id != -1 %>
  <% if request.referer == "http://192.168.20.229:3000/groups/out_top/#{current_user.state_group_id}" %>

    <% @group = Group.where("id = ?", current_user.state_group_id).first %>
    <% if @group.master_id == current_user.id %>

      <% @member = Member.where("group_id = ?", current_user.state_group_id).where("p = ?", 0) %>
      <% @i = 0 %>
      <% @member.each do |m| %>
        <% @i = @i + 1 %>
      <% end %>
      <% if @i != 0 %>
        <script type="text/javascript">
          alert("管理者様へ" + "\n" + "団体への参加申請が届いています");
        </script>
      <% end %>

    <% end %>

  <% end %>
<% end %>

<!-------------------------------------->

app/views/posts/_member.html.erb
  <% if current_user.state_group_id == -1 || current_user.state_group_id == nil%>
  <% else%>
    <h3>
      <%= link_to 'Member', members_show_path  ,class: "memberlink"%>
    </h3>

    <ul >
      <% @group = Group.where("id = ?", current_user.state_group_id).first %>
      <% @master = User.where("id = ?", @group.master_id).first %>

      <li style = list-style:circle >
        <p><%= link_to @master.username, "/users/#{@group.master_id}",class: "linkline4" %></p>
      </li>


      <% @member = Member.where("group_id = ?", current_user.state_group_id).where("p = ?", 1 ) %>
      <% @member.each do |p|%>
      <li style = list-style:circle>
        <% @user = User.where("id = ?", p.user_id).first %>
        <p><%= link_to @user.username, "/users/#{p.user_id}",class: "linkline" %></p>
      </li>
      <% end%>
    </ul>
  <%end%>

app/views/posts/_profile.html.erb
<div class = "dropposi">
  <ul id = "fade-in2" class="dropmenu">
    <li><%= image_tag('edit_b.png', class: 'edit_b') %>
      <ul>
        <li><%= link_to "Profile",current_user%></li>
        <li><%= link_to "Edit",edit_user_registration_path%></li>
        <li><%= link_to 'Logout', destroy_user_session_path, method: :delete%></li>
      </ul>
    </li>
  </ul>
</div>
  <br>
  <br>

  <h1 align = "center">
    <% @user = User.where("id = ?", current_user.id).first %>
    <%= link_to @user.username ,current_user,class: "prolink"%>
  </h1>

  <div class = "profile">
    <% if current_user.image? %>
      <%= link_to image_tag(current_user.image.url), current_user %>
    <% else %>
      <%= link_to image_tag('apio.png', :size => '100x100'), current_user %>
    <% end %>

    <h2>
      自己紹介
    </h2>
    </div>
    <div class ="center">
    <% @user = User.where("id = ?", current_user.id).first %>
    <% if @user.comment.empty? %>
      <%= link_to "自己紹介を書きましょう", user_root_path ,class: "linkline3"%>
    <% else%>
      <%= simple_format @user.comment %>
    <% end %>
    </div>

    <br>
  <div class = "profile">
    <h2>
      団体一覧
    </h2>

    <% @group = Group.where("master_id = ?", current_user.id) %>
    <% @group.each do |p| %>
    <li style = list-style:circle>
      <% if p.id == current_user.state_group_id %>
        <!--<p><%= link_to p.name, "/groups/top/#{p.id}" ,class: "statecolor" %></p>-->
	       <p><font color="hotpink"><%= p.name %>◀︎︎</font></p>
      <% else %>
        <p><%= link_to p.name, "/groups/out_top/#{p.id}" ,class: "linkline"%></p>
      <% end %>
    </li>
    <% end %>

    <% @member = Member.where("user_id = ?", current_user.id).where("p = ?", 1 ) %>
    <% @member.each do |p| %>
      <% @group2 = Group.where("id = ?", p.group_id).first%>
      <li style = list-style:circle>
        <% if @group2.id == current_user.state_group_id %>
          <p><%= link_to @group2.name, "/groups/top/#{@group2.id}" ,class: "statecolor" %></p>
        <% else %>
          <p><%= link_to @group2.name, "/groups/out_top/#{@group2.id}" ,class: "linkline"%></p>
        <% end %>
      </li>
      <% end%>

    <br>
    <br>
  </div>

app/views/posts/club_list.html.erb
<%= link_to "新規団体作成", "/groups/new" ,class: "logout"%>
<section class = "column">

  <div class="titleposi">
    <h1>
      Myclub
    </h1>
  </div>
  <h3>
    管理団体
  </h3>

    <ul>
      <% @group = Group.where("master_id = ?", current_user.id) %>
      <% if @group.empty? %>
        <p>管理団体はありません</p>
      <% else %>
        <% @group.each do |p| %>
        <li style = list-style:circle>
          <% if p.id == current_user.state_group_id %>
  	    <%= link_to p.name, "/members/applicater/#{p.id}",class: "statecolor" %>
          <% else %>
  	    <%= link_to p.name,"/members/applicater/#{p.id}" ,class: "linkline"%>
          <% end %>
          <% @member = Member.where("group_id = ?", p.id).where("p = ?", 0) %>
          <% @i = 0 %>
          <% @member.each do |m| %>
          <% @i = @i + 1 %>
          <% end %>
          <% if @i != 0 %>
           （承認待ち: <%= @i %>人）
          <% end %>
        </li>
        <% end %>
      <% end %>
    </ul>

  <h3>
    所属団体
  </h3>

    <ul>
      <% @member = Member.where("user_id = ?", current_user.id).where("p = ?", 1 ) %>
      <% if @member.empty? %>
        <p>所属団体はありません</p>
      <% else %>
        <% @member.each do |p| %>
        <% @group = Group.where("id = ?", p.group_id).first%>
        <li style = list-style:circle>
          <% if @group.id == current_user.state_group_id %>
            <p><%= link_to @group.name, "/groups/top/#{@group.id}" ,class: "statecolor" %></p>

              <% @tmp = Group.where("id = ?", current_user.state_group_id).first %>
              <% if @tmp != nil && @tmp.master_id == current_user.id then %>
              <% else %>
              <% if current_user.state_group_id != -1 then %>
              <%= link_to "退会", "/members/retire", data:{confirm:"本当に「#{@tmp.name}」を退会しますか?"},class: "linkline2"%>
              <% else %>
              <% end %>
              <% end %>
          <% else %>
            <p><%= link_to @group.name, "/groups/out_top/#{@group.id}" ,class: "linkline"%></p>
          <% end %>
        </li>
        <% end%>
      <% end %>
    </ul>

   <h3>
    申請中の団体
  </h3>
    <ul class="linklist">
      <% @member = Member.where("user_id = ?", current_user.id).where("p = ?", 0 ) %>
      <% if @member.empty? %>
        <p>申請中の団体はありません</p>
      <% else %>
        <% @member.each do |p| %>
        <% @group = Group.where("id = ?", p.group_id).first%>
        <li>
          <p><%= link_to @group.name, "/groups/out_top/#{@group.id}" ,class: "linkline"%></p>
        </li>
        <% end%>
      <% end %>
    </ul>

</section>

app/views/posts/edit.html.erb
<section class = "column">
  <div class = "titleposi">
<h1>Edit Post</h1>
  </div>
<%= render 'form' %>
</section>

app/views/posts/index.html.erb
<!-- pagebodymain -->

  <%= render "main" %>

app/views/posts/new.html.erb
<section class = "column">

<div class = "titleposi">
  <h1>Add NewPost</h1>
</div>

<%= render 'form' %>
</section>

app/views/posts/show.html.erb
<section class = "column">
  <div class = "titleposi">

  <h1><%= @post.title %></h1>
</div>
  <h3><%= simple_format @post.body %></h3>
  <!--最終更新：<%= time_ago_in_words(@post.created_at) %>
  <br>
  -->
  作成：<%= @post.created_at.strftime('%Y/%m/%d %H:%M') %> Created at <%= link_to @post.username, "/users/#{@post.user_id}" ,class: "linkline"%>
  <br>
  更新：<%= @post.updated_at.strftime('%Y/%m/%d %H:%M') %>
  <br><br><br>
  <% if (@post.user_id == current_user.id) %>
  <%= link_to image_tag('edit_bb.png', class: 'edit_bb'), edit_post_path(@post)%>

  <% end %>

  <!-- コメントの表示 -->
  <h3>Comments</h3>
  <% if @post.comments.any? %>
  <ul>
    <% @post.comments.each do |comment| %>
    <li>
      <%= comment.created_at.strftime('%Y/%m/%d %H:%M') %> Created at <%= link_to comment.username, "/users/#{comment.user_id}" ,class: "linkline"%>
      <br>
      内容：<%= comment.body %>
      <div class = "right">
      <%= link_to '[X]',
        post_comment_path(@post, comment),
        method: :delete,
        class: 'command',
        data: { confirm: 'Sure?' } ,class: "linkline"%>
        <div>
    </li>
    <% end %>
  </ul>
  <% end %>

  <%= form_for ([@post, @post.comments.build]) do |f| %>
  <p>
    <%= f.text_field :body, placeholder: 'comment' %>
  </p>
  <p>
    <%= f.submit value = "コメント" %>
  </p>
  <% end %>
  <br>
  <% if (@post.user_id == current_user.id) %>
  <h4 align = "center"><%= link_to 'この記事を削除する',
  post_path(@post),
  method: :delete,
  class: 'command',
    data: { confirm: 'Sure?' },
    class:"cross_line"
  %></h4>

  <%end%>
</section>